### ISSUE TITLE
Need more detailed installation guides

### ISSUE THREAD

**Issue by westNeighbor** [warmshao/FasterLivePortrait#1]
First time to install tensorrt, follow the [official instructions](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html), not sure succeeded to install tensorrt. 
Try to run, get the following errors, does this indicates I am not succeeded in installing tensorrt?
![Screenshot 2024-07-16 143718](https://github.com/user-attachments/assets/484392e7-a871-4505-aeed-b057db56b3c4)

Can you please give more detailed information guides?

**Comment by westNeighbor** [comment]
The above problem solved. I am using local environments, so need to install tensorrt python packages for that local python. But in Windows, couldn't successfully compile onnxruntime.
![Screenshot 2024-07-16 175126](https://github.com/user-attachments/assets/497db93f-9d26-419b-b0bb-caddc26d9848)

**Comment by warmshao** [comment]
> The above problem solved. I am using local environments, so need to install tensorrt python packages for that local python. But in Windows, couldn't successfully compile onnxruntime. ![Screenshot 2024-07-16 175126](https://private-user-images.githubusercontent.com/143965219/349296529-497db93f-9d26-419b-b0bb-caddc26d9848.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNzA5MTAsIm5iZiI6MTcyMTE3MDYxMCwicGF0aCI6Ii8xNDM5NjUyMTkvMzQ5Mjk2NTI5LTQ5N2RiOTNmLTlkMjYtNDE5Yi1iMGJiLWNhZGRjMjZkOTg0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQyMjU2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjdlNTkzMzU4OWRhMjU5Zjc0NjZlZmNkNmY5N2IxYWY0NTJjOTFmZTVkOGNiZjcyNThlZTZlZTRkYjM4ZmMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LEkZTtf_01OBvR22XYGeGkdcI2hl60IxOn6jN7-yR50)

hi, the README tutorial is for Linux. I haven't tried installing TensorRT and building ONNXRUNTIME-GPU from source on Windows yet, but I expect there might be some challenges. I suggest using Docker or Docker Compose.

**Comment by warmshao** [comment]
> The above problem solved. I am using local environments, so need to install tensorrt python packages for that local python. But in Windows, couldn't successfully compile onnxruntime. ![Screenshot 2024-07-16 175126](https://private-user-images.githubusercontent.com/143965219/349296529-497db93f-9d26-419b-b0bb-caddc26d9848.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNzA5MTAsIm5iZiI6MTcyMTE3MDYxMCwicGF0aCI6Ii8xNDM5NjUyMTkvMzQ5Mjk2NTI5LTQ5N2RiOTNmLTlkMjYtNDE5Yi1iMGJiLWNhZGRjMjZkOTg0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQyMjU2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjdlNTkzMzU4OWRhMjU5Zjc0NjZlZmNkNmY5N2IxYWY0NTJjOTFmZTVkOGNiZjcyNThlZTZlZTRkYjM4ZmMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LEkZTtf_01OBvR22XYGeGkdcI2hl60IxOn6jN7-yR50)

Wait for me to finish experimenting on Windows, and I will update the tutorial. Give me a few days, or feel free to submit a pull request.

**Comment by warmshao** [comment]
> The above problem solved. I am using local environments, so need to install tensorrt python packages for that local python. But in Windows, couldn't successfully compile onnxruntime. ![Screenshot 2024-07-16 175126](https://private-user-images.githubusercontent.com/143965219/349296529-497db93f-9d26-419b-b0bb-caddc26d9848.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMjU5NTEsIm5iZiI6MTcyMTIyNTY1MSwicGF0aCI6Ii8xNDM5NjUyMTkvMzQ5Mjk2NTI5LTQ5N2RiOTNmLTlkMjYtNDE5Yi1iMGJiLWNhZGRjMjZkOTg0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QxNDE0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDlkYWYyNjgwMTBiZGZlNmYxODJlMTg3M2RjMGNkZjAyODZhZWM2MWE5Y2VmZGFkZjI1YzNjNjI2MjczMDVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n_MZ53qDTOfYX9nIJi7vxfqgLDNZK0w2Hq7V7z6Qvc4)

hi, I have uploaded an docker image that supports docker running FasterLivePortrait. Please try it out.

**Comment by zffffff** [comment]
有没有大佬做了comfyui的版本

**Comment by warmshao** [comment]
Using onnxruntime-gpu as the backend, an alpha version for Windows has been made. You guys can start by helping to experience it. After extracting, just run app.bat directly, and let me know if there are any issues. Please note that it is assumed you have already installed CUDA and cuDNN, and have set up the environment variables properly.

https://drive.google.com/file/d/1ijqDlMAYqAVlqwqlXDpjBS5i3A6R_f7M/view?usp=sharing

**Comment by aminesoulaymani** [comment]
> Using onnxruntime-gpu as the backend, an alpha version for Windows has been made. You guys can start by helping to experience it. After extracting, just run app.bat directly, and let me know if there are any issues. Please note that it is assumed you have already installed CUDA and cuDNN, and have set up the environment variables properly.
> 
> https://drive.google.com/file/d/1ijqDlMAYqAVlqwqlXDpjBS5i3A6R_f7M/view?usp=sharing

Error: No Python at 'C:\Users\wensh\AppData\Local\Programs\Python\Python310\python.exe'

**Comment by warmshao** [comment]
> > Using onnxruntime-gpu as the backend, an alpha version for Windows has been made. You guys can start by helping to experience it. After extracting, just run app.bat directly, and let me know if there are any issues. Please note that it is assumed you have already installed CUDA and cuDNN, and have set up the environment variables properly.
> > https://drive.google.com/file/d/1ijqDlMAYqAVlqwqlXDpjBS5i3A6R_f7M/view?usp=sharing
> 
> Error: No Python at 'C:\Users\wensh\AppData\Local\Programs\Python\Python310\python.exe'

Thank you for your feedback. Can you provide more error information?

**Comment by warmshao** [comment]
Hi guys, Install-free, extract-and-play Windows package with TensorRT support now available! Please watch change log, really fast!!!

**Comment by warmshao** [comment]
Animal model and mediapipe are supported now！Enjoy~
