### ISSUE TITLE
About performance with onnxruntime

### ISSUE THREAD

**Issue by Ryuukeisyou** [warmshao/FasterLivePortrait#100]
My env:
gpu nvidia 4090 
system windows
cuda 12.4
cudnn 9.1

I migrated onnxruntime code for grid_sample 5D from liqun/imageDecoder_cuda branch to the main branch and compiled. 
code is here https://github.com/Ryuukeisyou/onnxruntime
Now the onnxruntime is running at about 20fps (0.05s for each step) for inference only, not counting the pre or post processing.

I used the following to run the test, same with what in the readme:
`python run.py 
 --src_image assets/examples/source/s10.jpg 
 --dri_video assets/examples/driving/d14.mp4 
 --cfg configs/onnx_infer.yaml`

Does anybody know if this is the normal speed, or maybe I missed something when migrating? 
Any help would be appreciated, thanks!

**Comment by warmshao** [comment]
> python run.py --src_image assets/examples/source/s10.jpg --dri_video assets/examples/driving/d14.mp4 --cfg configs/onnx_infer.yaml

ensorRT. However, you need to follow the tutorial to install TensorRT, perform model conversion, and finally run： python run.py  --src_image assets/examples/source/s10.jpg  --dri_video assets/examples/driving/d14.mp4  --cfg configs/trt_infer.yaml

**Comment by Ryuukeisyou** [comment]
I tried tensorrt and it reaches 30~50 fps on different conditions. thank you!
