### ISSUE TITLE
Animation Region feature

### ISSUE THREAD

**Issue by tivikoff** [warmshao/FasterLivePortrait#101]
Hello. Do you have any plans to implement an Animation Region feature in the UI? To allow users to choose between animating everything or just pose/expression or separate eyes/lips. something similar to how it's implemented in the original LivePortrait: 
![image](https://github.com/user-attachments/assets/105402e9-a686-4a45-9618-47e6ef31dac7)
Thank you

**Comment by warmshao** [comment]
> Hello. Do you have any plans to implement an Animation Region feature in the UI? To allow users to choose between animating everything or just pose/expression or separate eyes/lips. something similar to how it's implemented in the original LivePortrait: ![image](https://private-user-images.githubusercontent.com/68391246/388542432-105402e9-a686-4a45-9618-47e6ef31dac7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMDI4MjksIm5iZiI6MTczMjIwMjUyOSwicGF0aCI6Ii82ODM5MTI0Ni8zODg1NDI0MzItMTA1NDAyZTktYTY4Ni00YTQ1LTk2MTgtNDdlNmVmMzFkYWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDE1MjIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0OGM0OTdjZWE1MjdmODBkOTE0YjgyMDVhODk5YTkxZmVmMzBjYjUyMmRiZDg4NzA1ODYzZTU5OTYxMzRhMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hXbVi-gJHutHjFTsVxQiILby7BsRsciyu3J_991X9jY) Thank you

I'm afraid I don't have time to implement this feature recently.

**Comment by warmshao** [comment]
support now~
