### ISSUE TITLE
JoyVASA support

### ISSUE THREAD

**Issue by apolinario** [warmshao/FasterLivePortrait#103]
JoyVASA uses LivePortrait as a backbone to its audio-driven talking heads. Would be great to have the audio-to-driving-sequence motion that JoyVASA uses in combination with FasterLivePortrait: https://github.com/jdh-algo/JoyVASA

**Comment by warmshao** [comment]
> JoyVASA uses LivePortrait as a backbone to its audio-driven talking heads. Would be great to have the audio-to-driving-sequence motion that JoyVASA uses in combination with FasterLivePortrait: https://github.com/jdh-algo/JoyVASA

Yes, I've noticed, and I will consider getting involved and accelerating the [JoyVASA](https://github.com/jdh-algo/JoyVASA).

**Comment by warmshao** [comment]
Support now! enjoy！
