### ISSUE TITLE
collaboration request

### ISSUE THREAD

**Issue by Vahe61** [warmshao/FasterLivePortrait#104]
I cant contact you via messengers. I want to collaborate. Please help me to install this program to to my PC and adjust it. I keep getting error. And what kind of payments do you accept? Do you have PayPal?

**Comment by warmshao** [comment]
> I cant contact you via messengers. I want to collaborate. Please help me to install this program to to my PC and adjust it. I keep getting error. And what kind of payments do you accept? Do you have PayPal?

add me on discord: warmshao

**Comment by Vahe61** [comment]
Ok. I have sent a friend request there
