### ISSUE TITLE
启动 webui.py 失败，缺少assets/examples/driving/d2.pkl

### ISSUE THREAD

**Issue by gttiankai** [warmshao/FasterLivePortrait#109]
如题，更新最新的代码，使用
```
python webui.py --mode trt 
```
启动 webui，会报错：
```
FileNotFoundError: [Errno 2] No such file or directory: 'assets/examples/driving/d2.pkl'
```

**Comment by gttiankai** [comment]
使用 run.py 推理之后会自己生成 pkl 文件，使用自己生成的 pkl 文件会报如下错误：
```
gradio.exceptions.Error: "Invalid file type. Please upload a file that is one of these formats: ['.pkl']"
```

**Comment by gttiankai** [comment]
目前上面的报错原因已经找到，和 gradio 的版本有关，是 gradio 版本太低了，识别不了 pkl 文件，升级gradio 到最新的版本就可以了

**Comment by warmshao** [comment]
> 如题，更新最新的代码，使用
> 
> ```
> python webui.py --mode trt 
> ```
> 
> 启动 webui，会报错：
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'assets/examples/driving/d2.pkl'
> ```

哦，这个文件忘记上传了，不过影响不大

**Comment by warmshao** [comment]
> 目前上面的报错原因已经找到，和 gradio 的版本有关，是 gradio 版本太低了，识别不了 pkl 文件，升级gradio 到最新的版本就可以了

OK
