### ISSUE TITLE
进入docker后gpu不可用

### ISSUE THREAD

**Issue by Gaojian00** [warmshao/FasterLivePortrait#114]
您好，我下载了您的镜像后，gpu不可用。输入nvidia-smi命令，提示NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH。修改环境变量等方法都尝试过了还是不行。

**Comment by warmshao** [comment]
参考这个解决 https://github.com/warmshao/FasterLivePortrait/issues/9

**Comment by Gaojian00** [comment]
> 参考这个解决 #9

感谢大佬！原来也是cuda的问题，顺利解决！再次感叹一句大佬太强了！

**Comment by warmshao** [comment]
✌️
