### ISSUE TITLE
JoyVasa implementation not working on Linux

### ISSUE THREAD

**Issue by apolinario** [warmshao/FasterLivePortrait#124]
This line seems to be a Windows specific hack/workaround 
              https://github.com/warmshao/FasterLivePortrait/blob/63367557518d3e9274617293970939b2b9039f3d/src/pipelines/joyvasa_audio_to_motion_pipeline.py#L32

When I try to run this code on Linux I get  
```shell
File "/usr/lib/python3.10/pathlib.py", line 962, in __new__
    raise NotImplementedError("cannot instantiate %r on your system"
NotImplementedError: cannot instantiate 'WindowsPath' on your system
```

If I remove this line it seems to load/work fine on Linux

**Comment by warmshao** [comment]
> This line seems to be a Windows specific hack/workaround
> 
> https://github.com/warmshao/FasterLivePortrait/blob/63367557518d3e9274617293970939b2b9039f3d/src/pipelines/joyvasa_audio_to_motion_pipeline.py#L32
> 
> When I try to run this code on Linux I get
> 
> ```shell
> File "/usr/lib/python3.10/pathlib.py", line 962, in __new__
>     raise NotImplementedError("cannot instantiate %r on your system"
> NotImplementedError: cannot instantiate 'WindowsPath' on your system
> ```
> 
> If I remove this line it seems to load/work fine on Linux

Thank you！I will fix this bug

**Comment by warmshao** [comment]
Should be fixed!

**Comment by apolinario** [comment]
Thanks!
