### ISSUE TITLE
分享一个关于Joyvasa出现“嘴巴张不开”问题的改善方法。

### ISSUE THREAD

**Issue by leetraman822** [warmshao/FasterLivePortrait#128]
首先感谢作者制作这个无敌的liveportrait整合包！

**Comment by leetraman822** [comment]
其实嘴巴张不开的主要原因，就是加载图片或视频的时候，下方do crop（source）旁边有一个source crop scale，这个默认是2.3，如果人物在朗读的时候，嘴巴很难张开，把2.3调低一些就好了，例如2，或者最低的1.8即可改善这个情况。

**Comment by leetraman822** [comment]
我初次尝试使用的是官方示例的蒙娜丽莎，一切都还挺好挺自然的，但是换了旁边的爱因斯坦，却发现嘴巴貌似很难张开，测试了部分官方提供的图片也是，开关relative motion也难以改善这种情况，感觉是人物面部重定向的问题，我甚至用官方的重定向功能进行了五官调整，例如嘴巴稍微张开一点，或闭紧一点，但是都没有改善。最后发现问题是出现在source crop scale这里。

**Comment by leetraman822** [comment]
https://github.com/user-attachments/assets/87457586-f3de-4694-a0b8-0fd39c760de7

分别测试了2.3（默认）、1.8（最低）、2，虽然嘴巴能张开了，但是嘴型在第一帧就张开看着可能会很奇怪，不过这个方法能改善嘴巴张不开的情况，期待joyvasa新版本。🥰

**Comment by warmshao** [comment]
> 12.28.mp4 
> 分别测试了2.3（默认）、1.8（最低）、2，虽然嘴巴能张开了，但是嘴型在第一帧就张开看着可能会很奇怪，不过这个方法能改善嘴巴张不开的情况，期待joyvasa新版本。🥰

666 感谢提醒~

**Comment by leetraman822** [comment]
@warmshao 大佬，生成的结果画质码率有点低，有没有办法改善呀？我的原视频总比特率是1161kbps，生成后的是721kbps。

**Comment by warmshao** [comment]
> @warmshao 大佬，生成的结果画质码率有点低，有没有办法改善呀？我的原视频总比特率是1161kbps，生成后的是721kbps。

已加，提高了输出的视频码率
