### ISSUE TITLE
Installation Instructions for FasterLivePortrait on Windows 11 & Performance Comparison between ONNX and TensorRT

### ISSUE THREAD

**Issue by MarsEverythingTech** [warmshao/FasterLivePortrait#19]
Hi,

I'm trying to install FasterLivePortrait on Windows 11 and found the guide in the installation section difficult to understand and follow. Could you please provide a more detailed step-by-step guide specifically for Windows 11? Any additional clarifications or tips would be greatly appreciated.

Additionally, I would like to understand which processing method—ONNX or TensorRT—is faster for this setup. I have TensorRT 10 and CUDA 11.8 installed. If there are notable performance differences, I’d like to choose the processing option that offers the best speed.

Thank you for your assistance!

Best regards

**Comment by warmshao** [comment]
Fow NOW，I recommend using docker in windows，and Tensorrt is faster

**Comment by MarsEverythingTech** [comment]
> Fow NOW，I recommend using docker in windows，and Tensorrt is faster

Thank you for the recommendations. I appreciate the guidance on using Docker and TensorRT.

However, I’m still finding the instructions for setting up Docker and configuring TensorRT a bit challenging to follow. Could you provide more detailed steps or clarify the following points?

Docker Setup:

Could you provide a step-by-step guide on how to set up Docker for this specific use case? Any specific configurations or commands would be very helpful.

TensorRT Integration:

How exactly should TensorRT be integrated into the FasterLivePortrait setup? Are there specific configuration files or settings that I need to adjust?
Any additional guidance or resources would be greatly appreciated.

Thank you for your continued assistance!

**Comment by warmshao** [comment]
> > Fow NOW，I recommend using docker in windows，and Tensorrt is faster
> 
> Thank you for the recommendations. I appreciate the guidance on using Docker and TensorRT.
> 
> However, I’m still finding the instructions for setting up Docker and configuring TensorRT a bit challenging to follow. Could you provide more detailed steps or clarify the following points?
> 
> Docker Setup:
> 
> Could you provide a step-by-step guide on how to set up Docker for this specific use case? Any specific configurations or commands would be very helpful.
> 
> TensorRT Integration:
> 
> How exactly should TensorRT be integrated into the FasterLivePortrait setup? Are there specific configuration files or settings that I need to adjust? Any additional guidance or resources would be greatly appreciated.
> 
> Thank you for your continued assistance!

I will release an integrated package for the Windows operating system tonight. This package is installation-free and can be used with one click, without the need for any complicated environment setup or installation process.

**Comment by warmshao** [comment]
Hi guys, Install-free, extract-and-play Windows package with TensorRT support now available! Please watch change log, really fast!!!

**Comment by warmshao** [comment]
Animal model and mediapipe are both suppored now! Enjoy~
