### ISSUE TITLE
docker Error when call all_onnx2trt.sh: not found_onnx2trt.sh

### ISSUE THREAD

**Issue by ChenGXQQ** [warmshao/FasterLivePortrait#21]
I use docker on Windows. When I call all_onnx2trt.sh, I get the error below. Can you help me? Thanks!
```
(base) root@334401369c17:~/FasterLivePortrait# sh scripts/all_onnx2trt.sh
: not found_onnx2trt.sh: 2:
```

**Comment by warmshao** [comment]
Please list the scripts folder to check the; I suspect you did not correctly map the fasterlive portrait.

> I use docker on Windows. When I call all_onnx2trt.sh, I get the error below. Can you help me? Thanks!
> 
> ```
> (base) root@334401369c17:~/FasterLivePortrait# sh scripts/all_onnx2trt.sh
> : not found_onnx2trt.sh: 2:
> ```

Check the scripts folder to see if all_onnx2trt.shexists. I suspect you did not correctly map the fasterliveportrait root

**Comment by ChenGXQQ** [comment]
![l_245222570_2439_0a703a7803fb60e5e9270d7033890c6e](https://github.com/user-attachments/assets/18cd775a-a177-4124-954a-641e0646c104)

and this is the whole error message
```
(base) root@334401369c17:~/FasterLivePortrait# sh scripts/all_onnx2trt.sh
: not found_onnx2trt.sh: 2:
[07/23/2024-13:44:31] [TRT] [I] [MemUsageChange] Init CUDA: CPU +20, GPU +0, now: CPU 31, GPU 1215 (MiB)
[07/23/2024-13:44:36] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1460, GPU +266, now: CPU 1568, GPU 1481 (MiB)
/root/FasterLivePortrait/scripts/onnx2trt.py:57: DeprecationWarning: Use set_memory_pool_limit instead.
  self.config.max_workspace_size = 12 * (2 ** 30)  # 12 GB
Traceback (most recent call last):
  File "/root/FasterLivePortrait/scripts/onnx2trt.py", line 157, in <module>
    main(args)
  File "/root/FasterLivePortrait/scripts/onnx2trt.py", line 135, in main
    builder.create_network(args.onnx)
  File "/root/FasterLivePortrait/scripts/onnx2trt.py", line 88, in create_network
    with open(onnx_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/FasterLivePortrait/checkpoints/liveportrait_onnx/warping_spade-fix.onnx\r'
[07/23/2024-13:44:37] [TRT] [I] [MemUsageChange] Init CUDA: CPU +20, GPU +0, now: CPU 31, GPU 1215 (MiB)

```

**Comment by shaoguowen** [comment]
> '/root/FasterLivePortrait/checkpoints/liveportrait_onnx/warping_spade-fix.onnx\r'

pls refer this: https://blog.csdn.net/zkw_1998/article/details/111207132. It is a typical problem

**Comment by warmshao** [comment]
Install-free, extract-and-play Windows package with TensorRT support now available! Please watch change log, really fast!!!
