### ISSUE TITLE
关于  MimicMotion  速度是否能提升？

### ISSUE THREAD

**Issue by zhanghongyong123456** [warmshao/FasterLivePortrait#23]
请问 大佬   MimicMotion  如何能提高推理速度：
https://github.com/Tencent/MimicMotion
是否  也可以实现  onnx  或者   tensorrt  加速呢？

**Comment by warmshao** [comment]
你怎么知道我在做了？

**Comment by zhanghongyong123456** [comment]
> 你怎么知道我在做了？

我感觉 你实现了很火的  liveportrait 项目加速 ，那么很有可能也在考虑实现另一个  很火的  运动驱动项目。 尤其 对于运动驱动速度更是硬伤，只是感觉  运动驱动会不会比 表情驱动实现 难度大呢

**Comment by warmshao** [comment]
> > 你怎么知道我在做了？
> 
> 我感觉 你实现了很火的 liveportrait 项目加速 ，那么很有可能也在考虑实现另一个 很火的 运动驱动项目。 尤其 对于运动驱动速度更是硬伤，只是感觉 运动驱动会不会比 表情驱动实现 难度大呢

会难一些，但还好，不过感觉提速比较大还是得去研究一下怎么减少step的数量

**Comment by zhanghongyong123456** [comment]
> > > 你怎么知道我在做了？
> > 
> > 
> > 我感觉 你实现了很火的 liveportrait 项目加速 ，那么很有可能也在考虑实现另一个 很火的 运动驱动项目。 尤其 对于运动驱动速度更是硬伤，只是感觉 运动驱动会不会比 表情驱动实现 难度大呢
> 
> 会难一些，但还好，不过感觉提速比较大还是得去研究一下怎么减少step的数量

对于采样步数减少 ，现在都是采用  LCM  或者   lightning 模型 去实现 ，不确定能不能使用，或者使用之后，效果会不会下降

**Comment by warmshao** [comment]
> > > > 你怎么知道我在做了？
> > > 
> > > 
> > > 我感觉 你实现了很火的 liveportrait 项目加速 ，那么很有可能也在考虑实现另一个 很火的 运动驱动项目。 尤其 对于运动驱动速度更是硬伤，只是感觉 运动驱动会不会比 表情驱动实现 难度大呢
> > 
> > 
> > 会难一些，但还好，不过感觉提速比较大还是得去研究一下怎么减少step的数量
> 
> 对于采样步数减少 ，现在都是采用 LCM 或者 lightning 模型 去实现 ，不确定能不能使用，或者使用之后，效果会不会下降

感觉得基于mmmtion重新训lcm或lightning，直接plugin效果肯定不大行

**Comment by zhanghongyong123456** [comment]
> > > > > > > 你怎么知道我在做了？
> > > > > > 
> > > > > > 
> > > > > > 我感觉 你实现了很火的 liveportrait 项目加速 ，那么很有可能也在考虑实现另一个 很火的 运动驱动项目。 尤其 对于运动驱动速度更是硬伤，只是感觉 运动驱动会不会比 表情驱动实现 难度大呢
> > > > > 
> > > > > 
> > > > > 会难一些，但还好，不过感觉提速比较大还是得去研究一下怎么减少step的数量
> > > > 
> > > > 
> > > > 对于采样步数减少 ，现在都是采用 LCM 或者 lightning 模型 去实现 ，不确定能不能使用，或者使用之后，效果会不会下降
> > > 
> > > 
> > > 感觉得基于mmmtion重新训lcm或lightning，直接plugin效果肯定不大行
> > 
> > 
> > 这个得看 后续官方会不会出 基于lcm或lightning的 模型 了
> 
> 我做完trt他们还没有训的话，我就自己训一个🤔🤔

大佬，请收下我的膝盖
