### ISSUE TITLE
How To Enable Full Precision FP32 in Web Demo app.py?

### ISSUE THREAD

**Issue by MarsEverythingTech** [warmshao/FasterLivePortrait#29]
Hello,

I have successfully installed the one-click installer, and would like to use the full precision fp32 on the web demo app.py
How can I so it?

Thanks in advance

**Comment by warmshao** [comment]
> Hello,
> 
> I have successfully installed the one-click installer, and would like to use the full precision fp32 on the web demo app.py How can I so it?
> 
> Thanks in advance

Using FP32  leads to occupying more VRAM and being relatively slower. If you really want to use FP32, you need to append `-p fp32` to the end of every line of code in the `all_onnx2trt.bat` file to perform the conversion again with FP32 precision.

**Comment by warmshao** [comment]
I'm not sure if it can be adapted to CUDA 11.8, you can give it a try, if it doesn't work, you might need to install CUDA 12.2. Perhaps it's because fp32 has filled up your VRAM causing the shutdown, by the way, have you tried running with fp16?

**Comment by Echolink50** [comment]
Where has it been shown that fp32 gives better results?

**Comment by MarsEverythingTech** [comment]
> I'm not sure if it can be adapted to CUDA 11.8, you can give it a try, if it doesn't work, you might need to install CUDA 12.2. Perhaps it's because fp32 has filled up your VRAM causing the shutdown, by the way, have you tried running with fp16?

Well, it was working fine with CUDA 11.8 and fp16 which is the default installation (by just clicking the .bat file to convert). However, when I edited it by appending -p 32 at each line as you suggested. My PC shut down by itself half through the processing of a video. My VRAM usage was very low, so I don't think it was the cause.

**Comment by MarsEverythingTech** [comment]
> Where has it been shown that fp32 gives better results?

The difference is minimal, but it can be noticeable if you keep replaying the same generated result and compare it to the fp16

**Comment by warmshao** [comment]
> > I'm not sure if it can be adapted to CUDA 11.8, you can give it a try, if it doesn't work, you might need to install CUDA 12.2. Perhaps it's because fp32 has filled up your VRAM causing the shutdown, by the way, have you tried running with fp16?
> 
> Well, it was working fine with CUDA 11.8 and fp16 which is the default installation (by just clicking the .bat file to convert). However, when I edited it by appending -p 32 at each line as you suggested. My PC shut down by itself half through the processing of a video. My VRAM usage was very low, so I don't think it was the cause.

Enter this command: `.\venv\python.exe scripts\onnx2trt.py -o .\checkpoints\liveportrait_onnx\warping_spade-fix.onnx -p fp32`,  and show me what happened?
