### ISSUE TITLE
GPU load is too low when M1 Pro is running

### ISSUE THREAD

**Issue by HildaM** [warmshao/FasterLivePortrait#30]
When running the sample project on M1 chip, I found that the CPU load is high and GPU load is low.It should be because MPS is not called. 

Is it possible to add MPS support in the future?

**Comment by warmshao** [comment]
> When running the sample project on M1 chip, I found that the CPU load is high and GPU load is low.It should be because MPS is not called.
> 
> Is it possible to add MPS support in the future?

I've also noticed that because the 5D grid sample of onnxruntime has not yet implemented CoreML's acceleration, it's quite slow. I'm afraid this is not a feature I will prioritize in the future, as I am not familiar with CoreML optimizations. 😟

**Comment by nick4fake** [comment]
Any news?
