### ISSUE TITLE
Need to be able to flip the camera [feature request]

### ISSUE THREAD

**Issue by LuckyNES** [warmshao/FasterLivePortrait#32]
I noticed when I look a certain direction it looks the opposite way. Can we add a command line attribute to camera.bat to allow me to flip horizontally? Thank you.
Update: To be clear, I want to flip horizontally the input from my camera that controls the output.

**Comment by warmshao** [comment]
你可以自己在这行代码https://github.com/warmshao/FasterLivePortrait/blob/13dcf8c0b326641d68e891edd0114fd4f9f923a9/run.py#L60 下面加上 frame = cv2.flip(frame, 1)

**Comment by LuckyNES** [comment]
Thank you!

**Comment by warmshao** [comment]
you are welcome
