### ISSUE TITLE
In addition to the Insightface model, are you considering supporting MediaPipe?

### ISSUE THREAD

**Issue by watch-activity** [warmshao/FasterLivePortrait#34]
The ComfyUI version of LivePortrait is now compatible, so I would like you to consider making this compatible as well.
https://github.com/kijai/ComfyUI-LivePortraitKJ

**Comment by watch-activity** [comment]
Thank you so much, I count on you!

**Comment by SystemPanic** [comment]
Another interested here.

Mediapipe face is the most famous and broadly used on browsers, and then send the landmarks to a server with FasterLivePortrait is very useful.

Thank you for your job!

**Comment by salahzoubi** [comment]
@warmshao have you managed to get Mediapipe integrated/done by any chance?

**Comment by warmshao** [comment]
> @warmshao have you managed to get Mediapipe integrated/done by any chance?

maybe tonight

**Comment by warmshao** [comment]
Animal model and mediapipe are supported now! Enjoy~
