### ISSUE TITLE
X-Pose for keypoints？

### ISSUE THREAD

**Issue by singlinhaha** [warmshao/FasterLivePortrait#41]
我看到有其他开发者使用X-Pose检测关键点，从而实现在动物脸上使用LivePortrait。我对这个不是很了解，请问一下在这个仓库中能否使用X-Pose检测器代替原项目中的Insightface，从而实现动物表情迁移？
仓库链接：https://github.com/ShiJiaying/LivePortrait/tree/main

**Comment by warmshao** [comment]
感觉当前模型在animal上的泛化性有限，我还想等作者发布他微调后的animal模型后再接入

**Comment by singlinhaha** [comment]
> 感觉当前模型在animal上的泛化性有限，我还想等作者发布他微调后的animal模型后再接入

好的，感谢您的回答！
