### ISSUE TITLE
视频对视频速度非常快，非常感谢！但是重点来了：源视频经过驱动视频驱动后并不能产生新的正确视频，而联排视频反而正确！请作者试试一下！

### ISSUE THREAD

**Issue by alin2688** [warmshao/FasterLivePortrait#43]
如题

**Comment by alin2688** [comment]
不知为什么时好时错，错时重启cmd就好,素材比较长，5min的视频，我的设备为Windows+12G3080ti+64内存。。。。。。

**Comment by warmshao** [comment]
> 不知为什么时好时错，错时重启cmd就好,素材比较长，5min的视频，我的设备为Windows+12G3080ti+64内存。。。。。。

没大明白你的意思，联排视频是啥？方便的话，可以把结果视频放上来，另外如果能复现的话，把复现流程发我

**Comment by alin2688** [comment]
现在使用软件都很正常了，正常得我都怀疑自己了。。。。。。现在动物模式也已出来，期待你的佳作。。。

**Comment by warmshao** [comment]
> 现在使用软件都很正常了，正常得我都怀疑自己了。。。。。。现在动物模式也已出来，期待你的佳作。。。

现在支持了
