### ISSUE TITLE
output video file size is much larger than the official one

### ISSUE THREAD

**Issue by westNeighbor** [warmshao/FasterLivePortrait#44]
I noticed that the output video file from your project is much larger than the official one, mainly because the output of yours have much larger Data rate and Total bitrate, I am wondering if there are any advantages to keep this large file size?

**Comment by warmshao** [comment]
> I noticed that the output video file from your project is much larger than the official one, mainly because the output of yours have much larger Data rate and Total bitrate, I am wondering if there are any advantages to keep this large file size?

更高清吧，不过 ffmpeg可以设置码率和crf，降低size

**Comment by warmshao** [comment]
You can update the "-b:v", "10M" in the ffmpeg command to a smaller value, such as "-b:v", "5M", to achieve a smaller video file size.
