### ISSUE TITLE
Any plan to support animal model?

### ISSUE THREAD

**Issue by yuananf** [warmshao/FasterLivePortrait#46]
https://github.com/KwaiVGI/LivePortrait/blob/main/assets/docs/changelog/2024-08-02.md

**Comment by warmshao** [comment]
> https://github.com/KwaiVGI/LivePortrait/blob/main/assets/docs/changelog/2024-08-02.md

tonight or tomorrow，stay tuned

**Comment by yuananf** [comment]
> > https://github.com/KwaiVGI/LivePortrait/blob/main/assets/docs/changelog/2024-08-02.md
> 
> tonight or tomorrow，stay tuned

Thank you!
And there are also some tips which will accelerate the process.
1. use cupy instead of numpy in paste_back
2. compile ffmpeg so it can use cuda, then replace 'libx264' with 'h264_nvenc'

**Comment by warmshao** [comment]
> > > https://github.com/KwaiVGI/LivePortrait/blob/main/assets/docs/changelog/2024-08-02.md
> > 
> > 
> > tonight or tomorrow，stay tuned
> 
> Thank you! And there are also some tips which will accelerate the process.
> 
> 1. use cupy instead of numpy in paste_back
> 2. compile ffmpeg so it can use cuda, then replace 'libx264' with 'h264_nvenc'

Thanks, I will update in the next version, but PRs are welcome.

**Comment by warmshao** [comment]
Animal model is supported now! enjoy~
