### ISSUE TITLE
Windows整合包版本提示No module named 'mediapipe'

### ISSUE THREAD

**Issue by leetraman822** [warmshao/FasterLivePortrait#48]
似乎我是缺少了mediapipe吗？😳

source image: [assets\examples\source\s12.jpg]
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.13 (you have 1.4.11). Upgrade using: pip install --upgrade albumentations
Traceback (most recent call last):
  File "E:\StableDiffusion\FasterLivePortrait-windows-20240807\run.py", line 26, in <module>
    from src.pipelines.faster_live_portrait_pipeline import FasterLivePortraitPipeline
  File "E:\StableDiffusion\FasterLivePortrait-windows-20240807\src\pipelines\faster_live_portrait_pipeline.py", line 17, in <module>
    from .. import models
  File "E:\StableDiffusion\FasterLivePortrait-windows-20240807\src\models\__init__.py", line 13, in <module>
    from .mediapipe_face_model import MediaPipeFaceModel
  File "E:\StableDiffusion\FasterLivePortrait-windows-20240807\src\models\mediapipe_face_model.py", line 8, in <module>
    import mediapipe as mp
ModuleNotFoundError: No module named 'mediapipe'

**Comment by leetraman822** [comment]
https://github.com/user-attachments/assets/74755525-a8b0-49cf-b6bb-9b8ec8d5ffa3

大佬好，由于我对python语言编程没有系统学习过，我今天尝试学习了一点python知识，通过询问GPT，制作了一个简单的针对此项目中的实时摄像头交互功能使用的webui。
现在可以直接在webui中上传或切换目标图像，不用再手动修改和反复启动批处理命令了。
如视频中演示的那样，webui有些不完善的地方，例如“clear、submit、flag”按钮全都是gradio默认提供的，我还不知道如何修改他们的文本。
不过基础的功能是可以正常使用的，如果出现之前的cv resize错误，那么右边的flag窗口就会有信息，这时候重新点击submit就行了，直到render窗口弹出为止。然后按Q键退出窗口，等待flag窗口出现日志，就可以继续选择下一个图像或操作。
如果大佬不介意的话，我会直接把这个简单的webui代码和启动bat命令发到这里。
您觉得是否有必要呢？

**Comment by warmshao** [comment]
> 8.7.mp4 
> @warmshao 大佬好，由于我对python语言编程没有系统学习过，我今天尝试学习了一点python知识，通过询问GPT，制作了一个简单的针对此项目中的实时摄像头交互功能使用的webui。 现在可以直接在webui中上传或切换目标图像，不用再手动修改和反复启动批处理命令了。 如视频中演示的那样，webui有些不完善的地方，例如“clear、submit、flag”按钮全都是gradio默认提供的，我还不知道如何修改他们的文本。 不过基础的功能是可以正常使用的，如果出现之前的cv resize错误，那么右边的flag窗口就会有信息，这时候重新点击submit就行了，直到render窗口弹出为止。然后按Q键退出窗口，等待flag窗口出现日志，就可以继续选择下一个图像或操作。 如果大佬不介意的话，我会直接把这个简单的webui代码和启动bat命令发到这里。 您觉得是否有必要呢？

很酷呀！可以呀，欢迎~

**Comment by leetraman822** [comment]
好的，webui.py的代码如下：

import gradio as gr
import subprocess

# 示例回调函数，需要根据您的实际需求进行调整
def process_image(img_path):
    # 构造命令行参数
    command = [
        ".\\venv\\python.exe",
        ".\\run.py",
        "--cfg",
        "configs/trt_infer.yaml",
        "--realtime",
        "--dri_video",
        "0",
        "--src_image",
        img_path
    ]
    
    # 执行命令
    result = subprocess.run(command, capture_output=True, text=True)
    
    # 返回命令执行结果
    return result.stdout

# 创建 Gradio 界面
iface = gr.Interface(
    fn=process_image,
    inputs="file",
    outputs="text",
    title="实时面部控制交互",
    description="1.请确保摄像头启用，并使摄像头画面中有人脸。2.选择一张图像，点击submit开始。3.若想要结束，在render窗口中按下Q键退出窗口，等待右侧flag窗口中出现日志文件，再进行下一步操作。"
)

iface.launch(inbrowser=True)

if __name__=="__main__":
    gradio_interface()

**Comment by leetraman822** [comment]
启动webui.bat的批处理命令如下：

@echo off
setlocal enabledelayedexpansion

call python webui.py

endlocal
pause

**Comment by leetraman822** [comment]
不知道上述的两篇代码有没有疏漏或者多余的地方，希望大佬有空可以帮忙优化改进一下，例如把submit这样的文本提示替换成“开始处理”之类的哈哈😂

**Comment by warmshao** [comment]
> 不知道上述的两篇代码有没有疏漏或者多余的地方，希望大佬有空可以帮忙优化改进一下，例如把submit这样的文本提示替换成“开始处理”之类的哈哈😂

问题不大，能用就行😁👍

**Comment by warmshao** [comment]
It has been fixed
