### ISSUE TITLE
Error When Launching app.py

### ISSUE THREAD

**Issue by MarsEverythingTech** [warmshao/FasterLivePortrait#49]
Hello, 

I just installed the latest Windows One-Click Installer, the did all_onnx2trt.bat, however, I am getting this error when I launch app.py:
OSError: [WinError 126] The specified module could not be found. Error loading "C:\FasterLivePortrait\venv\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

Thanks in advance

**Comment by warmshao** [comment]
> Hello,
> 
> I just installed the latest Windows One-Click Installer, the did all_onnx2trt.bat, however, I am getting this error when I launch app.py: OSError: [WinError 126] The specified module could not be found. Error loading "C:\FasterLivePortrait\venv\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
> 
> Thanks in advance

It might be some issues with the local environment, try to resolve them in this way：https://discuss.pytorch.org/t/failed-to-import-pytorch-fbgemm-dll-or-one-of-its-dependencies-is-missing/201969

**Comment by MarsEverythingTech** [comment]
> > Hello,
> > I just installed the latest Windows One-Click Installer, the did all_onnx2trt.bat, however, I am getting this error when I launch app.py: OSError: [WinError 126] The specified module could not be found. Error loading "C:\FasterLivePortrait\venv\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
> > Thanks in advance
> 
> It might be some issues with the local environment, try to resolve them in this way：https://discuss.pytorch.org/t/failed-to-import-pytorch-fbgemm-dll-or-one-of-its-dependencies-is-missing/201969

Thanks, I fixed it by installing VS Community 2022. However, I am getting this error now:

  File "C:\FasterLivePortrait\src\models\mediapipe_face_model.py", line 8, in <module>
    import mediapipe as mp
ModuleNotFoundError: No module named 'mediapipe'

**Comment by warmshao** [comment]
😅，I should have fixed it in https://github.com/warmshao/FasterLivePortrait/issues/48，You can install it by running .\venv\python.exe -m pip install mediapipe anyway

**Comment by MarsEverythingTech** [comment]
> 😅，I should have fixed it in (#48) You can install it by running .\venv\python.exe -m pip install mediapipe

Thanks, I fixed it. Where my results will be saved? 
Also, why the head becomes small when I press do crop (driving)?

**Comment by warmshao** [comment]
> > 😅，I should have fixed it in (#48) You can install it by running .\venv\python.exe -m pip install mediapipe
> 
> Thanks, I fixed it. Where my results will be saved? Also, why the head becomes small when I press do crop (driving)?

1. There is a download button in the upper right corner of the result video; just click it to download the video directly. Alternatively, if you want to find the video, you can go to a folder named "results" under the root directory of the project , and look for it according to the date.
2. I haven't tried crop driving yet, I will debug it when I have time.

**Comment by MarsEverythingTech** [comment]
> > > 😅，I should have fixed it in (#48) You can install it by running .\venv\python.exe -m pip install mediapipe
> > 
> > 
> > Thanks, I fixed it. Where my results will be saved? Also, why the head becomes small when I press do crop (driving)?
> 
> 1. There is a download button in the upper right corner of the result video; just click it to download the video directly. Alternatively, if you want to find the video, you can go to a folder named "results" under the root directory of the project , and look for it according to the date.
> 2. I haven't tried crop driving yet, I will debug it when I have time.

Oh, thanks! How can I know if it is processing fast? For example, a 11 second 60fps driving video took me 70 seconds.

**Comment by warmshao** [comment]
> > > > 😅，I should have fixed it in (#48) You can install it by running .\venv\python.exe -m pip install mediapipe
> > > 
> > > 
> > > Thanks, I fixed it. Where my results will be saved? Also, why the head becomes small when I press do crop (driving)?
> > 
> > 
> > 
> > 1. There is a download button in the upper right corner of the result video; just click it to download the video directly. Alternatively, if you want to find the video, you can go to a folder named "results" under the root directory of the project , and look for it according to the date.
> > 2. I haven't tried crop driving yet, I will debug it when I have time.
> 
> Oh, thanks! How can I know if it is processing fast? For example, a 11 second 60fps driving video took me 70 seconds.

Here's the translation for your message:

You can do a speed comparison yourself with the original PyTorch repository. I've tested on multiple machines, and TensorRT is definitely faster than PyTorch.

**Comment by MarsEverythingTech** [comment]
> > > > > 😅，I should have fixed it in (#48) You can install it by running .\venv\python.exe -m pip install mediapipe
> > > > 
> > > > 
> > > > Thanks, I fixed it. Where my results will be saved? Also, why the head becomes small when I press do crop (driving)?
> > > 
> > > 
> > > 
> > > 1. There is a download button in the upper right corner of the result video; just click it to download the video directly. Alternatively, if you want to find the video, you can go to a folder named "results" under the root directory of the project , and look for it according to the date.
> > > 2. I haven't tried crop driving yet, I will debug it when I have time.
> > 
> > 
> > Oh, thanks! How can I know if it is processing fast? For example, a 11 second 60fps driving video took me 70
> 
> You can do a speed comparison yourself with the original PyTorch repository. I've tested on multiple machines, and TensorRT is definitely faster than PyTorch.

Yes for sure it is faster than PyTorch. I will test it. I am now getting an audio issue. When I launch the Gradio App, and play the generated video with audio, the audio produces a sound just like here: https://www.youtube.com/watch?v=w7-4jJqQzvQ
However, when I restart my PC, and not launch the Gradio App, the sound is normal.
