### ISSUE TITLE
Albumentations needs version update, mediapipe missing (Windows standalone)

### ISSUE THREAD

**Issue by LuckyNES** [warmshao/FasterLivePortrait#60]
I am using this version of the WIndows standalone: FasterLivePortrait-windows-20240807.zip
I have not had issues before, but on this newest one I get these errors when running camera.bat

D:\Tools\FasterLivePortrait>camera.bat
source image: [assets\examples\source\s12.jpg]
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.13 (you have 1.4.11). Upgrade using: pip install --upgrade albumentations
Traceback (most recent call last):
  File "D:\Tools\FasterLivePortrait\run.py", line 26, in <module>
    from src.pipelines.faster_live_portrait_pipeline import FasterLivePortraitPipeline
  File "D:\Tools\FasterLivePortrait\src\pipelines\faster_live_portrait_pipeline.py", line 17, in <module>
    from .. import models
  File "D:\Tools\FasterLivePortrait\src\models\__init__.py", line 13, in <module>
    from .mediapipe_face_model import MediaPipeFaceModel
  File "D:\Tools\FasterLivePortrait\src\models\mediapipe_face_model.py", line 8, in <module>
    import mediapipe as mp
ModuleNotFoundError: No module named 'mediapipe'

**Comment by leetraman822** [comment]
I have had this problem before, you can refer to the method here to solve it.https://github.com/warmshao/FasterLivePortrait/issues/48#issuecomment-2273499229

**Comment by warmshao** [comment]
> I have had this problem before, you can refer to the method here to solve it.[#48 (comment)](https://github.com/warmshao/FasterLivePortrait/issues/48#issuecomment-2273499229)

Thank you 
@LuckyNES You can refer to this for a solution, I will fix this bugand update the package.

**Comment by warmshao** [comment]
It has been fixed
