### ISSUE TITLE
this happens when i run app.bat in the packaged win version

### ISSUE THREAD

**Issue by marsonal2023** [warmshao/FasterLivePortrait#62]
![image](https://github.com/user-attachments/assets/dc68ab15-d7e9-4d97-a96e-e4abd7dc58e4)

**Comment by warmshao** [comment]
You have not converted the ONNX model to the TRT model. Please double-click the 'all_onnx2trt.bat' to perform the conversion, and refer to the README for detailed instructions on how to use it.

**Comment by tivikoff** [comment]
@warmshao Hello. Just not to create separate issue, I converted onnx to trt. But when running app.bat it shows error:

```
C:\Users\Admin\Neural\FasterLivePortrait-windows-20240807>.\venv\python.exe .\app.py --mode trt
Traceback (most recent call last):
  File "C:\Users\Admin\Neural\FasterLivePortrait-windows-20240807\app.py", line 11, in <module>
    from src.pipelines.gradio_live_portrait_pipeline import GradioLivePortraitPipeline
  File "C:\Users\Admin\Neural\FasterLivePortrait-windows-20240807\src\pipelines\gradio_live_portrait_pipeline.py", line 16, in <module>
    from .faster_live_portrait_pipeline import FasterLivePortraitPipeline
  File "C:\Users\Admin\Neural\FasterLivePortrait-windows-20240807\src\pipelines\faster_live_portrait_pipeline.py", line 15, in <module>
    import torch
  File "C:\Users\Admin\Neural\FasterLivePortrait-windows-20240807\venv\lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Admin\Neural\FasterLivePortrait-windows-20240807\venv\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
```

Installed CUDA 12.2, extracted cuDNN, latest VC++ redistr. 
Win10 x64, RTX2070S

What it could be? The web search offers also installing C/C++ compiler, but I don't know if it's neccessary in our case. Thanks

**Comment by warmshao** [comment]
> @warmshao Hello. Just not to create separate issue, I converted onnx to trt. But when running app.bat it shows error:
> 
> ```
> C:\Users\Admin\Neural\FasterLivePortrait-windows-20240807>.\venv\python.exe .\app.py --mode trt
> Traceback (most recent call last):
>   File "C:\Users\Admin\Neural\FasterLivePortrait-windows-20240807\app.py", line 11, in <module>
>     from src.pipelines.gradio_live_portrait_pipeline import GradioLivePortraitPipeline
>   File "C:\Users\Admin\Neural\FasterLivePortrait-windows-20240807\src\pipelines\gradio_live_portrait_pipeline.py", line 16, in <module>
>     from .faster_live_portrait_pipeline import FasterLivePortraitPipeline
>   File "C:\Users\Admin\Neural\FasterLivePortrait-windows-20240807\src\pipelines\faster_live_portrait_pipeline.py", line 15, in <module>
>     import torch
>   File "C:\Users\Admin\Neural\FasterLivePortrait-windows-20240807\venv\lib\site-packages\torch\__init__.py", line 148, in <module>
>     raise err
> OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Admin\Neural\FasterLivePortrait-windows-20240807\venv\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
> ```
> 
> Installed CUDA 12.2, extracted cuDNN, latest VC++ redistr. Win10 x64, RTX2070S
> 
> What it could be? The web search offers also installing C/C++ compiler, but I don't know if it's neccessary in our case. Thanks

in case if you dont want to download visual studio. [https://www.dllme.com/dll/files/libomp140_x86_64?sort=upload&arch=0x8664 1.8k](https://www.dllme.com/dll/files/libomp140_x86_64?sort=upload&arch=0x8664) you can just download this dll and place it in windows/system32 directory. it works as well too  

ref:https://discuss.pytorch.org/t/failed-to-import-pytorch-fbgemm-dll-or-one-of-its-dependencies-is-missing/201969/12

**Comment by marsonal2023** [comment]
thanks worked
