### ISSUE TITLE
Strange cropping results in "animal mode"

### ISSUE THREAD

**Issue by tivikoff** [warmshao/FasterLivePortrait#64]
Hello. I'm in the middle of testing of the new animal mode.
With human images it works flawlessly as I can see:
![image](https://github.com/user-attachments/assets/57af89e5-1bbc-4c83-8df4-a957a85c808e)

But when I  use source image of animal, and tick the checkbox "is_animal" - it produces some weird results, but nothing close to good animation. Looks like some glitches with cropping or detecting animal faces.
![image](https://github.com/user-attachments/assets/97f6248a-0b87-4616-8609-502fb687ee16)

Tested multiple times - result always is the same.

Also have some issues with source video mode (it shows "error in ms_deformable_im2col_cuda: no kernel image is available for execution on the device"), but I think this is the topic for another issue.

Thanks for your work and support!

Windows package from 0810

**Comment by warmshao** [comment]
This should be a problem with the compilation of Xposed ops, you can try to compile it yourself to solve it in the following way:
.\venv\python.exe src\models\XPose\models\UniPose\ops\setup.py build install

**Comment by warmshao** [comment]
> Hello. I'm in the middle of testing of the new animal mode. With human images it works flawlessly as I can see: ![image](https://private-user-images.githubusercontent.com/68391246/356826649-57af89e5-1bbc-4c83-8df4-a957a85c808e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNzExOTEsIm5iZiI6MTcyMzM3MDg5MSwicGF0aCI6Ii82ODM5MTI0Ni8zNTY4MjY2NDktNTdhZjg5ZTUtMWJiYy00YzgzLThkZjQtYTk1N2E4NWM4MDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDEwMDgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YmZlODQxNzJkMDRmZjQwZTc0NzcwZWMxMThjMTFmZTViMGU0YTk0YzE4ZDE4ZmQ2ZmQ5YmJiNDMxNWNlMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2y-pgUuqm4eEarJMQ4SNL7zAdHshov3aGv5UGgdWO3w)
> 
> But when I use source image of animal, and tick the checkbox "is_animal" - it produces some weird results, but nothing close to good animation. Looks like some glitches with cropping or detecting animal faces. ![image](https://private-user-images.githubusercontent.com/68391246/356826732-97f6248a-0b87-4616-8609-502fb687ee16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNzExOTEsIm5iZiI6MTcyMzM3MDg5MSwicGF0aCI6Ii82ODM5MTI0Ni8zNTY4MjY3MzItOTdmNjI0OGEtMGI4Ny00NjE2LTg2MDktNTAyZmI2ODdlZTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDEwMDgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MWJjNTg1YzUxOGNkZjIwZjUyNWVjYmQwYTVmYTBkZDBhYjE5ZTJhZDU2NTdlN2M4YzQ5OGEzMDA3OTBmZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2Jy8vgykPpaxnonjBfwU-CDf6nTFlv1cB7fGvBNi-4w)
> 
> Tested multiple times - result always is the same.
> 
> Also have some issues with source video mode (it shows "error in ms_deformable_im2col_cuda: no kernel image is available for execution on the device"), but I think this is the topic for another issue.
> 
> Thanks for your work and support!
> 
> Windows package from 0810

If you don't want to install, the latest Windows integration package 0811 should have fixed it, but you will need to re-download.

**Comment by tivikoff** [comment]
It's fixed now. Thank you!
