### ISSUE TITLE
Would it be possible to have a Video Guide for Beginners

### ISSUE THREAD

**Issue by oisilener1982** [warmshao/FasterLivePortrait#7]
Im not a programmer and doesnt know much. Would it be possible for someone to create a video tutorial about how to install docker and fasterliveportrait? 

Liveportrait is already working but i want to try FasterLivePortrait.

We need something similar to this video, with very simple instructions  https://www.youtube.com/watch?v=bRHf2oQwgG4&t=179s

**Comment by warmshao** [comment]
sure，stay tuned

**Comment by watch-activity** [comment]
I made a simple video for beginners.
The commands used are also included in the video.
https://youtu.be/9NozmyH05zU?si=teto1GIf-5KbOSpI

**Comment by Echolink50** [comment]
Is this possible to run on windows without docker? Thanks

**Comment by warmshao** [comment]
> Is this possible to run on windows without docker? Thanks

It is possible, I am still working on it.

**Comment by Echolink50** [comment]
If you could provide good documentation on how to install when it's released that would be great. Thanks

**Comment by warmshao** [comment]
Using onnxruntime-gpu as the backend, an alpha version for Windows has been made. You guys can start by helping to experience it. After extracting, just run app.bat directly, and let me know if there are any issues. Please note that it is assumed you have already installed CUDA and cuDNN, and have set up the environment variables properly.

https://drive.google.com/file/d/1ijqDlMAYqAVlqwqlXDpjBS5i3A6R_f7M/view?usp=sharing

It's very easy to use, perhaps a tutorial is no longer necessary.

**Comment by FurkanGozukara** [comment]
@warmshao thanks a lot

by the way i have excellent tutorial for how to setup python cuda c++ tools : https://youtu.be/-NjNy7afOQ0

**Comment by warmshao** [comment]
> @warmshao thanks a lot
> 
> by the way i have excellent tutorial for how to setup python cuda c++ tools : https://youtu.be/-NjNy7afOQ0

You're very welcome! Appreciate the tutorial you shared.

**Comment by warmshao** [comment]
I have verified that transferring the Python virtual environment to another Windows computer does indeed cause some issues. I am still working on resolving this. Thank you for your feedback. Stay tuned！

**Comment by warmshao** [comment]
> Can this do video to video?

Not yet, but I've found that LivePortrait has already implemented it; I'll integrate it when I have time.

**Comment by warmshao** [comment]
Hi guys, Install-free, extract-and-play Windows package with TensorRT support now available! Please watch change log, really fast!!!

**Comment by oisilener1982** [comment]
Please share the link

![Capture](https://github.com/user-attachments/assets/2639b3fa-92cb-4cb8-bcde-08d42af014ae)

**Comment by warmshao** [comment]
> Please share the link
> 
> ![Capture](https://private-user-images.githubusercontent.com/29243313/351921159-2639b3fa-92cb-4cb8-bcde-08d42af014ae.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4Njk1NjEsIm5iZiI6MTcyMTg2OTI2MSwicGF0aCI6Ii8yOTI0MzMxMy8zNTE5MjExNTktMjYzOWIzZmEtOTJjYi00Y2I4LWJjZGUtMDhkNDJhZjAxNGFlLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAxMDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NTEwMDAzZTRkODhhNjRjOGRiOTYyMzk2ZGRhNjY0YWFiMzZjNDVkOWQ1MzA2MTU2YTFlMWE2NGFiOGFkZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8VoYGnw535uLESgA_TOJHpkLb7s1EpJmUubkUMY6oXA)

refer releases page: https://github.com/warmshao/FasterLivePortrait/releases/tag/v1.1

**Comment by warmshao** [comment]
Animal model and mediapipe are supported now！Enjoy~
