### ISSUE TITLE
onnx to trt

### ISSUE THREAD

**Issue by TZYSJTU** [warmshao/FasterLivePortrait#72]
Hi, could you offer the code of translating onnx to trt? I would like to use my A10

**Comment by warmshao** [comment]
ref：scripts/onnx2trt.py

**Comment by TZYSJTU** [comment]
> ref：scripts/onnx2trt.py

thanks，and may I ask which one is the pth to onnx scripts?

**Comment by warmshao** [comment]
> > ref：scripts/onnx2trt.py
> 
> thanks，and may I ask which one is the pth to onnx scripts?

ref: https://github.com/warmshao/LivePortrait/blob/anim/export_onnx.py
