### ISSUE TITLE
救命，web无法启动

### ISSUE THREAD

**Issue by overaverage** [warmshao/FasterLivePortrait#74]
![微信截图_20240813175826](https://github.com/user-attachments/assets/2a87c524-a45e-438d-8f15-04a7fd218908)
它到这里就一直不动了，无法启动web

**Comment by warmshao** [comment]
这个已经算成功了呀，你手动打开网页就好了

**Comment by overaverage** [comment]
> 这个已经算成功了呀，你手动打开网页就好了

手动打开是直接在浏览器中输入http://localhost:9870/么？

**Comment by warmshao** [comment]
> > 这个已经算成功了呀，你手动打开网页就好了
> 
> 手动打开是直接在浏览器中输入[http://localhost:9870/么？](http://localhost:9870/%E4%B9%88%EF%BC%9F)

是啊，localhost不行的话就127.0.0.1

**Comment by overaverage** [comment]
> > > 这个已经算成功了呀，你手动打开网页就好了
> > 
> > 
> > 手动打开是直接在浏览器中输入 [http://localhost:9870/ 么？](http://localhost:9870/%E4%B9%88%EF%BC%9F)
> 
> 是啊，localhost不行的话就127.0.0.1

![image](https://github.com/user-attachments/assets/7328d55c-a808-44af-8fef-349bbfa26a38)
可以打开了，但是生成的时候出现了错误

**Comment by warmshao** [comment]
> > > > 这个已经算成功了呀，你手动打开网页就好了
> > > 
> > > 
> > > 手动打开是直接在浏览器中输入 [http://localhost:9870/ 么？](http://localhost:9870/%E4%B9%88%EF%BC%9F)
> > 
> > 
> > 是啊，localhost不行的话就127.0.0.1
> 
> ![image](https://private-user-images.githubusercontent.com/128167405/357372556-7328d55c-a808-44af-8fef-349bbfa26a38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDgwMjYsIm5iZiI6MTcyMzU0NzcyNiwicGF0aCI6Ii8xMjgxNjc0MDUvMzU3MzcyNTU2LTczMjhkNTVjLWE4MDgtNDRhZi04ZmVmLTM0OWJiZmEyNmEzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMTE1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWQ0NDE5NmM4N2M5MWE5NmYzM2NhZjAyNWIyNGUyOTYyY2JhZTY3NDk4OGI2ZTVkOTBhZjBiYzVlN2U5M2IyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.58MgDufcWo18usfercO2KAZ07sOsy87b2BWg4cjYjZ4) 可以打开了，但是生成的时候出现了错误

你有上传正确的视频文件么

**Comment by overaverage** [comment]
> > > > > 这个已经算成功了呀，你手动打开网页就好了
> > > > 
> > > > 
> > > > 手动打开是直接在浏览器中输入 [http://localhost:9870/ 么？](http://localhost:9870/%E4%B9%88%EF%BC%9F)
> > > 
> > > 
> > > 是啊，localhost不行的话就127.0.0.1
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/128167405/357372556-7328d55c-a808-44af-8fef-349bbfa26a38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDgwMjYsIm5iZiI6MTcyMzU0NzcyNiwicGF0aCI6Ii8xMjgxNjc0MDUvMzU3MzcyNTU2LTczMjhkNTVjLWE4MDgtNDRhZi04ZmVmLTM0OWJiZmEyNmEzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMTE1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWQ0NDE5NmM4N2M5MWE5NmYzM2NhZjAyNWIyNGUyOTYyY2JhZTY3NDk4OGI2ZTVkOTBhZjBiYzVlN2U5M2IyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.58MgDufcWo18usfercO2KAZ07sOsy87b2BWg4cjYjZ4)可以打开了，但是生成的时候出现了错误
> 
> 你有上传正确的视频文件么

可以了，是我没安装虚拟环境，现在好了，谢谢~
