### ISSUE TITLE
any plan to update new features from official?

### ISSUE THREAD

**Issue by westNeighbor** [warmshao/FasterLivePortrait#79]
Hello,

The official has new cool features, any plan to follow up?

**Comment by warmshao** [comment]
> Hello,
> 
> The official has new cool features, any plan to follow up?

 I don't have time recently. It will need some time before I can get to it.

**Comment by westNeighbor** [comment]
cool, glad to hear they are on plan. Also, can you give the option to save the cut one. Currently the cut one is concatenated with the driving source, sometimes people really just want the cut one cause the paste back flicking too much.

**Comment by Mayorc1978** [comment]
> > Hello,
> > The official has new cool features, any plan to follow up?
> 
> I don't have time recently. It will need some time before I can get to it.

Please add Image(source)ToImage(driving) realtime support.

**Comment by warmshao** [comment]
> > > Hello,
> > > The official has new cool features, any plan to follow up?
> > 
> > 
> > I don't have time recently. It will need some time before I can get to it.
> 
> Please add Image(source)ToImage(driving) realtime support.

OK, waiting for next update, stay tuned!

**Comment by Mayorc1978** [comment]
> > > > Hello,
> > > > The official has new cool features, any plan to follow up?
> > > 
> > > 
> > > I don't have time recently. It will need some time before I can get to it.
> > 
> > 
> > Please add Image(source)ToImage(driving) realtime support.
> 
> OK, waiting for next update, stay tuned!

Has the Realtime img2img support been added?

**Comment by warmshao** [comment]
done!
