### ISSUE TITLE
install additional python package

### ISSUE THREAD

**Issue by jaehyunshinML** [warmshao/FasterLivePortrait#81]
Hi 
your no install windows package works great and easy ! thanks!
Just a quick question.
If I want to install additional package into yours, how can I do it ?

thanks!

**Comment by warmshao** [comment]
> Hi your no install windows package works great and easy ! thanks! Just a quick question. If I want to install additional package into yours, how can I do it ?
> 
> thanks!

.\venv\python.exe -m pip install xxx

**Comment by jaehyunshinML** [comment]
Thanks for the reply. I tried that .\venv\python.exe -m pip install xxx, but got this error 

after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000023507AF8730>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))': /pip/


it seems you used proxy setting. do you know where to disable them ?

Many Thanks!
