### ISSUE TITLE
paste back result error of the xxx_org.mp4

### ISSUE THREAD

**Issue by TZYSJTU** [warmshao/FasterLivePortrait#82]
Hi, I have compiled trt successfully in my machine.
But I found the generated result of xxx_org.mp4 is just a still video of the input image.
While the xxx_crop.mp4 is right.
What's wrong with this?  maybe ffmpeg?

**Comment by warmshao** [comment]
> Hi, I have compiled trt successfully in my machine. But I found the generated result of xxx_org.mp4 is just a still video of the input image. While the xxx_crop.mp4 is right. What's wrong with this? maybe ffmpeg?

Add --paste_back after the command line. Also, please read the readme tutorial first.

**Comment by TZYSJTU** [comment]
> > Hi, I have compiled trt successfully in my machine. But I found the generated result of xxx_org.mp4 is just a still video of the input image. While the xxx_crop.mp4 is right. What's wrong with this? maybe ffmpeg?
> 
> Add --paste_back after the command line. Also, please read the readme tutorial first.

Thanks, it works. 
I suggest --paste_back to be set to default=True, or you do not have to save the xxx_org.mp4 result since it is meaningness.
