### ISSUE TITLE
Can you add the motion template driving option?

### ISSUE THREAD

**Issue by westNeighbor** [warmshao/FasterLivePortrait#84]
Hello,
Can you please add the auto-generated motion template process and also give an option to use the motion template as driving source? I really like to use yours cause it's so fast, but the lack of this option bothers me because I have to use the official one to achieve them. Thank you!

**Comment by warmshao** [comment]
> Hello, Can you please add the auto-generated motion template process and also give an option to use the motion template as driving source? I really like to use yours cause it's so fast, but the lack of this option bothers me because I have to use the official one to achieve them. Thank you!

OK，Stay tuned. Kind of busy recently😂

**Comment by warmshao** [comment]
done~
