### ISSUE TITLE
测试 vid2vid，发现 驱动完视频粘贴不回去？

### ISSUE THREAD

**Issue by zhanghongyong123456** [warmshao/FasterLivePortrait#86]
这是测试结果

https://github.com/user-attachments/assets/72c16db1-5be8-4f63-a29d-94fd1a6886d4

https://github.com/user-attachments/assets/6053d396-5f39-4b52-967e-135581d79944

使用原项目 可以粘贴回去

https://github.com/user-attachments/assets/c53b70e3-576e-459b-b819-0777af762b2a

https://github.com/user-attachments/assets/636d9b29-4b51-4128-a202-3df8515ea748

这是因为什么，这是我的驱动视频  

https://github.com/user-attachments/assets/68a62bb3-e152-4dfc-9227-aa25d6fa7965

**Comment by YacratesWyh** [comment]
怀疑是stitching

**Comment by warmshao** [comment]
> 这是测试结果
> 
>  s18.mp4-20240906_113356_01_mfcc_pose_only.mp4-crop-audio.mp4 
> 
>  s18.mp4-20240906_113356_01_mfcc_pose_only.mp4-org-audio.mp4 
> 
> 使用原项目 可以粘贴回去
> 
>  s18--20240906_113356_01_mfcc_pose_only_concat.mp4 
> 
>  s18--20240906_113356_01_mfcc_pose_only.mp4 
> 
> 这是因为什么，这是我的驱动视频
> 
>  20240906_113356_01_mfcc_pose_only.mp4

source video和driving video发一下

**Comment by zhanghongyong123456** [comment]
> > 这是测试结果
> > s18.mp4-20240906_113356_01_mfcc_pose_only.mp4-crop-audio.mp4
> > s18.mp4-20240906_113356_01_mfcc_pose_only.mp4-org-audio.mp4
> > 使用原项目 可以粘贴回去
> > s18--20240906_113356_01_mfcc_pose_only_concat.mp4
> > s18--20240906_113356_01_mfcc_pose_only.mp4
> > 这是因为什么，这是我的驱动视频
> > 20240906_113356_01_mfcc_pose_only.mp4
> 
> source video和driving video发一下

驱动视频就是最下面这个https://private-user-images.githubusercontent.com/48466610/365349853-68a62bb3-e152-4dfc-9227-aa25d6fa7965.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjA2MTgsIm5iZiI6MTcyNjAyMDMxOCwicGF0aCI6Ii80ODQ2NjYxMC8zNjUzNDk4NTMtNjhhNjJiYjMtZTE1Mi00ZGZjLTkyMjctYWEyNWQ2ZmE3OTY1Lm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDAyMDUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNTdkNDBjODIyNTFhNmFhMjE2ZmExOTc0MDIyMTYzNDFhYjAzY2E4ODcxY2RlYjNiNzA

https://github.com/user-attachments/assets/72d32b65-2b98-4bf3-ad50-bd268a36ac7d

zMjMxZGRiNjZmZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Uul_PUJFApoRpdBznbQk5vFzKlX3QDA0kNc6pT02HyQ ，原视频是 原项目的  s18 视频

**Comment by warmshao** [comment]
> > > 这是测试结果
> > > s18.mp4-20240906_113356_01_mfcc_pose_only.mp4-crop-audio.mp4
> > > s18.mp4-20240906_113356_01_mfcc_pose_only.mp4-org-audio.mp4
> > > 使用原项目 可以粘贴回去
> > > s18--20240906_113356_01_mfcc_pose_only_concat.mp4
> > > s18--20240906_113356_01_mfcc_pose_only.mp4
> > > 这是因为什么，这是我的驱动视频
> > > 20240906_113356_01_mfcc_pose_only.mp4
> > 
> > 
> > source video和driving video发一下
> 
> 驱动视频就是最下面这个https://private-user-images.githubusercontent.com/48466610/365349853-68a62bb3-e152-4dfc-9227-aa25d6fa7965.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjA2MTgsIm5iZiI6MTcyNjAyMDMxOCwicGF0aCI6Ii80ODQ2NjYxMC8zNjUzNDk4NTMtNjhhNjJiYjMtZTE1Mi00ZGZjLTkyMjctYWEyNWQ2ZmE3OTY1Lm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDAyMDUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNTdkNDBjODIyNTFhNmFhMjE2ZmExOTc0MDIyMTYzNDFhYjAzY2E4ODcxY2RlYjNiNzAzMjMxZGRiNjZmZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Uul_PUJFApoRpdBznbQk5vFzKlX3QDA0kNc6pT02HyQ ，原视频是 原项目的 s18 视频 https://github.com/user-attachments/assets/72d32b65-2b98-4bf3-ad50-bd268a36ac7d

我看你的demo也是paste back，只是效果比不上原始的对吧？一个可能的原因是 相对于原仓库，v2v我还没有加上smooth，等我找时间加上smooth试试

**Comment by zhanghongyong123456** [comment]
> > 这是测试结果
> > s18.mp4-20240906_113356_01_mfcc_pose_only.mp4-crop-audio.mp4
> > s18.mp4-20240906_113356_01_mfcc_pose_only.mp4-org-audio.mp4
> > 使用原项目 可以粘贴回去
> > s18--20240906_113356_01_mfcc_pose_only_concat.mp4
> > s18--20240906_113356_01_mfcc_pose_only.mp4
> > 这是因为什么，这是我的驱动视频
> > 20240906_113356_01_mfcc_pose_only.mp4
> 
> 现在应该修复了，看最新的代码




  这是新代码测试结果：
https://github.com/user-attachments/assets/79af37fc-3ba8-4f62-a0f6-7dcdb9030ef3
确实好很多，新的测试结果，有一种伸脖子感觉，有一部分闪烁的厉害
