### ISSUE TITLE
build [ERROR] - Float 8 types require CUDA>=11.8. They must be disabled on CUDA==11.7

### ISSUE THREAD

**Issue by God-YYB** [warmshao/FasterLivePortrait#9]
docker里的cuda版本是11.7，意思还是用自己服务器上的cuda吗
或者使用系统提示的这个选项： Add '--disable_types float8' to your command line. See option disable_types.

**Comment by warmshao** [comment]
> docker里的cuda版本是11.7，意思还是用自己服务器上的cuda吗 或者使用系统提示的这个选项： Add '--disable_types float8' to your command line. See option disable_types.

用我的镜像的话，就没必要安装onnxruntime了，都装好了

**Comment by God-YYB** [comment]
> > docker里的cuda版本是11.7，意思还是用自己服务器上的cuda吗 或者使用系统提示的这个选项： Add '--disable_types float8' to your command line. See option disable_types.
> 
> 用我的镜像的话，就没必要安装onnxruntime了，都装好了
明白了，但在执行推理命令的时候
ImportError: /usr/lib/x86_64-linux-gnu/libcuda.so.1: file too short
(base) root@043b4f260e97:~/FasterLivePortrait# ls -l /usr/lib/x86_64-linux-gnu/libcuda.so.1
-r-xr-xr-x 1 root root 0 Jul 17 08:41 /usr/lib/x86_64-linux-gnu/libcuda.so.1
查看到这个文件应该是受损了

**Comment by warmshao** [comment]
> > > docker里的cuda版本是11.7，意思还是用自己服务器上的cuda吗 或者使用系统提示的这个选项： Add '--disable_types float8' to your command line. See option disable_types.
> > 
> > 
> > 用我的镜像的话，就没必要安装onnxruntime了，都装好了
> > 明白了，但在执行推理命令的时候
> > ImportError: /usr/lib/x86_64-linux-gnu/libcuda.so.1: file too short
> > (base) root@043b4f260e97:~/FasterLivePortrait# ls -l /usr/lib/x86_64-linux-gnu/libcuda.so.1
> > -r-xr-xr-x 1 root root 0 Jul 17 08:41 /usr/lib/x86_64-linux-gnu/libcuda.so.1
> > 查看到这个文件应该是受损了

ls -lh /usr/lib/x86_64-linux-gnu/看一下你自己的cuda so文件，然后建立软连接试试，cuda的问题确实比较麻烦😡
ln -sf /usr/lib/x86_64-linux-gnu/xxx.so /usr/lib/x86_64-linux-gnu/libcuda.so.1

**Comment by God-YYB** [comment]
经过查找，我发现这个文件的大小是0，然后搜到了一些别的文件也存在这些问题，请问大佬能提供一下这个文件夹或者下面几个文件的下载链接吗，非常感谢！
(base) root@6fddf8ba7f43:~/FasterLivePortrait# ls -lh /usr/lib/x86_64-linux-gnu/libcuda.so* 
lrwxrwxrwx 1 root root  12 Jul 17 08:41 /usr/lib/x86_64-linux-gnu/libcuda.so -> libcuda.so.1
-r-xr-xr-x 1 root root   0 Jul 17 08:41 /usr/lib/x86_64-linux-gnu/libcuda.so.1
-rw-r--r-- 1 root root 21M Feb 27  2023 /usr/lib/x86_64-linux-gnu/libcuda.so.515.105.01
-rw-r--r-- 1 root root 28M Feb 28 20:43 /usr/lib/x86_64-linux-gnu/libcuda.so.550.54.14
拷贝出错的文件路径：
(base) root@6fddf8ba7f43:~/FasterLivePortrait# find /usr/lib/x86_64-linux-gnu -type f -size 0
/usr/lib/x86_64-linux-gnu/libdxcore.so
/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
/usr/lib/x86_64-linux-gnu/libcudadebugger.so.1
/usr/lib/x86_64-linux-gnu/libcuda.so.1

**Comment by God-YYB** [comment]
> > > > docker里的cuda版本是11.7，意思还是用自己服务器上的cuda吗 或者使用系统提示的这个选项： Add '--disable_types float8' to your command line. See option disable_types.
> > > 
> > > 
> > > 用我的镜像的话，就没必要安装onnxruntime了，都装好了
> > > 明白了，但在执行推理命令的时候
> > > ImportError: /usr/lib/x86_64-linux-gnu/libcuda.so.1: file too short
> > > (base) root@043b4f260e97:~/FasterLivePortrait# ls -l /usr/lib/x86_64-linux-gnu/libcuda.so.1
> > > -r-xr-xr-x 1 root root 0 Jul 17 08:41 /usr/lib/x86_64-linux-gnu/libcuda.so.1
> > > 查看到这个文件应该是受损了
> 
> ls -lh /usr/lib/x86_64-linux-gnu/看一下你自己的cuda so文件，然后建立软连接试试，cuda的问题确实比较麻烦😡 ln -sf /usr/lib/x86_64-linux-gnu/xxx.so /usr/lib/x86_64-linux-gnu/libcuda.so.1

经过查找，我发现这个文件的大小是0，然后搜到了一些别的文件也存在这些问题，请问大佬能提供一下这个文件夹或者下面几个文件的下载链接吗，非常感谢！
'(base) root@6fddf8ba7f43:/FasterLivePortrait# ls -lh /usr/lib/x86_64-linux-gnu/libcuda.so*
lrwxrwxrwx 1 root root 12 Jul 17 08:41 /usr/lib/x86_64-linux-gnu/libcuda.so -> libcuda.so.1
-r-xr-xr-x 1 root root 0 Jul 17 08:41 /usr/lib/x86_64-linux-gnu/libcuda.so.1
-rw-r--r-- 1 root root 21M Feb 27 2023 /usr/lib/x86_64-linux-gnu/libcuda.so.515.105.01
-rw-r--r-- 1 root root 28M Feb 28 20:43 /usr/lib/x86_64-linux-gnu/libcuda.so.550.54.14
'
拷贝出错的文件路径：
'(base) root@6fddf8ba7f43:/FasterLivePortrait# find /usr/lib/x86_64-linux-gnu -type f -size 0
/usr/lib/x86_64-linux-gnu/libdxcore.so
/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
/usr/lib/x86_64-linux-gnu/libcudadebugger.so.1
/usr/lib/x86_64-linux-gnu/libcuda.so.1
'

**Comment by warmshao** [comment]
> > rm /usr/lib/x86_64-linux-gnu/libcuda.so.1 ，然后ln -sf /usr/lib/x86_64-linux-gnu/libcuda.so.550.54.14 /usr/lib/x86_64-linux-gnu/libcuda.so.1 先看看行不行，我看你的550的大小不是0
> 
> ok！！！问题解决啦，谢谢大佬！！

enjoy😄
