### ISSUE TITLE
how can i run it on runpod in real time using tensor rt

### ISSUE THREAD

**Issue by AbhinavJangra29** [warmshao/FasterLivePortrait#93]
having difficulties in tensorrt installation on runpod , please help

**Comment by warmshao** [comment]
what is your problem?

**Comment by AbhinavJangra29** [comment]
this is my order of execution:
cloning your repo
req installation along with ffmpeg
 this is my base image:pytorch:2.1.1-py3.10-cuda12.1.1-devel-ubuntu22.04
 
 downlading onnx weights
 cloning and checking out onnxruntime branch given by you.
installing cmake(pip install cmake latest version)
 then running the build.sh:
 seems to run for a while around 60( constantly given cudnn.h not found error)
 so i download cudnn from the commands given on nvidia for cuda 12(mine is cuda12.5)
 this is the final result:

![image](https://github.com/user-attachments/assets/d6b398e3-376e-4ae3-a135-91282be55cef)

 
 could you please help with a more elaborative installation, i have been stuck with the isntallation for a long time now...

**Comment by warmshao** [comment]
> this is my order of execution: cloning your repo req installation along with ffmpeg this is my base image:pytorch:2.1.1-py3.10-cuda12.1.1-devel-ubuntu22.04
> 
> downlading onnx weights cloning and checking out onnxruntime branch given by you. installing cmake(pip install cmake latest version) then running the build.sh: seems to run for a while around 60( constantly given cudnn.h not found error) so i download cudnn from the commands given on nvidia for cuda 12(mine is cuda12.5) this is the final result:
> 
> ![image](https://private-user-images.githubusercontent.com/107471490/383126518-d6b398e3-376e-4ae3-a135-91282be55cef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MDY5NjcsIm5iZiI6MTczMDgwNjY2NywicGF0aCI6Ii8xMDc0NzE0OTAvMzgzMTI2NTE4LWQ2YjM5OGUzLTM3NmUtNGFlMy1hMTM1LTkxMjgyYmU1NWNlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxMTM3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iN2JmMmRmZDA0OWE4NGU2OWI4M2IwNTM5ZjBmZjg3NGY5NjUwYmRjZGUzMGRkMDE1YzAyZTVlOWUyNTI0NjMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eenTGqd-zN5TyKezm_4TxrJgBLaKR_UdhO6OoAJIZo4)
> 
> could you please help with a more elaborative installation, i have been stuck with the isntallation for a long time now...

The version of onnxruntime seems to have strict requirements for the version of CUDA. Your CUDA version is a bit high, and I'm not sure if that branch doesn't support it, especially since that branch is still in a developmental state. You need to raise an issue on onnxruntime to ask about it. Additionally, if you don't necessarily have to use onnxruntime for inference, and if you're only using onnxruntime, you can simply install it via pip with pip install onnxruntime.

**Comment by AbhinavJangra29** [comment]
okay i downgraded , it seems to run properly in onnxruntime inference. great.
moving on to tensor rt inference.
i have used : pip install tensorrt 
after that following the given commands:
git clone https://github.com/SeanWangJS/grid-sample3d-trt-plugin
cd grid-sample3d-trt-plugin
Modify line 30 in CMakeLists.txt to: set_target_properties(${PROJECT_NAME} PROPERTIES CUDA_ARCHITECTURES "60;70;75;80;86")
export PATH=/usr/local/cuda/bin:$PATH
mkdir build && cd build
cmake .. -DTensorRT_ROOT=usr/local/lib/python3.10/dist-packages/tensorrt
make

it gives:

![image](https://github.com/user-attachments/assets/a316abcb-c265-47e5-890a-b9b205a5b2e5)


seems like a header file is missing, i have tried to repeat this whole process but eventually ends up in the same way.

**Comment by AbhinavJangra29** [comment]
https://github.com/user-attachments/assets/cc039a34-8431-49e0-ad3e-c8e296a8092d


i can see cuda_fp16.h is present, still the issue

**Comment by AbhinavJangra29** [comment]
i guess its all about library versioning that needs to be well aligned, now im unable to replicate it again. can you please specify the libraries and the versions specifically
