### ISSUE TITLE
Please update the latest code of LivePortrait!

### ISSUE THREAD

**Issue by linhcentrio** [warmshao/FasterLivePortrait#94]
Please update the latest code of LivePortrait!
https://github.com/KwaiVGI/LivePortrait

**Comment by warmshao** [comment]
which part?

**Comment by linhcentrio** [comment]
> which part?

can you pls update "expression-friendly" and 📁 Driving Pickle
![image](https://github.com/user-attachments/assets/d7ea2d19-b470-4599-9fa2-733728eb1340)

**Comment by warmshao** [comment]
done
