### ISSUE TITLE
one onnx model giving error while conversion

### ISSUE THREAD

**Issue by AbhinavJangra29** [warmshao/FasterLivePortrait#96]
![image](https://github.com/user-attachments/assets/3774411f-b8c3-451a-980d-e15e15dcfe3e)

which leads to :  

![image](https://github.com/user-attachments/assets/aa7b8bba-5b49-4340-96a1-20a53f2b71ff)

cuda :11.8
torch : 2.0.0

**Comment by yakhyo** [comment]
hi @AbhinavJangra29 ,  could you tell how did you fix this? Thank you.
