### ISSUE TITLE
能提供gcc、cmake

### ISSUE THREAD

**Issue by Obito-github** [warmshao/FasterLivePortrait#98]

**Comment by Obito-github** [comment]
什么版本都没有，pip安装一堆错，好容易调对了gcc又和tensorrt、onnx的编译make的版本冲突了，折腾了一礼拜就是搞不出一个加速。。。。。。。。。。。。。。。

**Comment by warmshao** [comment]
> 什么版本都没有，pip安装一堆错，好容易调对了gcc又和tensorrt、onnx的编译make的版本冲突了，折腾了一礼拜就是搞不出一个加速。。。。。。。。。。。。。。。

看一下我提供的镜像啊，里面有 gcc 和 cmake 的版本
